use std::fs;
use std::path::PathBuf;
use std::process::Command;

use anyhow::{Context, Result};
use console::style;

use crate::commands::lab::services;
use crate::host::state;
use crate::plan::StepContext;

pub async fn run(
    sctx: &StepContext<'_>,
    port: u64,
    upstreams: &[String],
    zone: &str,
) -> Result<()> {
    if sctx.dry_run {
        println!(
            "{} [dry-run] would write registries.yaml, certs.d/, and lab-resolv.conf",
            style(">>>").yellow()
        );
        return Ok(());
    }

    let lab_name = sctx.lab_name;

    let state_dir = state::service_state_dir(lab_name, "registry");
    fs::create_dir_all(&state_dir).with_context(|| format!("creating {}", state_dir.display()))?;
    let registries_yaml = services::generate_registries_yaml(port as u16, upstreams);
    fs::write(state_dir.join("registries.yaml"), registries_yaml)
        .context("writing registries.yaml")?;

    let certs_d = state_dir.join("certs.d");
    let host_dir = certs_d.join(format!("registry.{zone}"));
    fs::create_dir_all(&host_dir).with_context(|| format!("creating {}", host_dir.display()))?;
    fs::write(
        host_dir.join("hosts.toml"),
        services::generate_registry_hosts_toml(zone),
    )
    .context("writing hosts.toml")?;
    let lab_ca_src = state::service_state_dir(lab_name, "proxy").join("ca.crt");
    if lab_ca_src.exists() {
        fs::copy(&lab_ca_src, host_dir.join("ca.crt")).context("copying lab CA into certs.d")?;
    } else {
        println!(
            "{} Lab CA missing at {}; registry pulls will fail until cert-generate produces it.",
            style("Warning:").yellow(),
            lab_ca_src.display(),
        );
    }

    let dns_server = probe_dns_container_ip();
    match dns_server {
        Some(ip) => {
            let resolv_path: PathBuf = state_dir.join("lab-resolv.conf");
            let content = format!(
                "# Auto-generated by catallaxy.\n\
                 # Lab DNS (Knot) handles *.<zone>; falls through on REFUSED.\n\
                 nameserver {ip}\n\
                 nameserver 1.1.1.1\n\
                 nameserver 8.8.8.8\n\
                 options timeout:1 attempts:1\n"
            );
            fs::write(&resolv_path, content).context("writing lab-resolv.conf")?;
        }
        None => {
            println!(
                "{} Could not resolve lab DNS container IP; k3d nodes \
                 will fall back to Docker DNS (lab hostnames won't resolve)",
                style("Warning:").yellow(),
            );
        }
    }

    Ok(())
}

fn probe_dns_container_ip() -> Option<String> {
    let output = Command::new("docker")
        .args([
            "inspect",
            "--format",
            "{{range .NetworkSettings.Networks}}{{.IPAddress}}\n{{end}}",
            "catallaxy-dns",
        ])
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    let stdout = String::from_utf8(output.stdout).ok()?;
    stdout
        .lines()
        .map(str::trim)
        .find(|l| !l.is_empty())
        .map(str::to_string)
}
