use std::collections::HashMap;
#[cfg(test)]
use std::io::Read;
use std::io::{BufRead, BufReader, Write};
use std::net::{TcpStream, ToSocketAddrs};
use std::time::Duration;

use anyhow::{Context, Result, anyhow, bail};
use console::style;

use crate::domain::{HostService, ServiceVolume};
use crate::io;

use crate::host::state::{lab_state_dir, service_state_dir};

pub fn k3d_host_endpoint() -> &'static str {
    "host.k3d.internal"
}

pub fn generate_registries_yaml(port: u16, upstreams: &[String]) -> String {
    let host = k3d_host_endpoint();
    let mut body = String::from("mirrors:\n");
    for h in upstreams {
        body.push_str(&format!(
            "  {h}:\n    endpoint: [\"http://{host}:{port}\"]\n"
        ));
    }
    body
}

pub fn lab_resolv_conf(dns_ip: &str) -> String {
    format!(
        "# Auto-generated by catallaxy.\n\
         # Lab DNS (Knot) handles *.<zone>; falls through on REFUSED.\n\
         nameserver {dns_ip}\n\
         nameserver 1.1.1.1\n\
         nameserver 8.8.8.8\n\
         options timeout:1 attempts:1\n"
    )
}

pub fn generate_registry_hosts_toml(zone: &str) -> String {
    format!(
        r#"# Auto-generated by catallaxy. Trusts the lab self-signed CA via
# `ca = ...`, so containerd verifies the Harbor cert against the same
# CA that signed it. DNS is handled by the lab DNS server (the k3d
# node's /etc/resolv.conf points at it), so this hosts.toml's only
# concern is TLS trust — no /etc/hosts hacks, no mirror semantics,
# no `?ns=` query, no `skip_verify`.
server = "https://registry.{zone}"

[host."https://registry.{zone}"]
  capabilities = ["pull", "resolve"]
  ca = "/var/lib/rancher/k3s/agent/etc/containerd/certs.d/registry.{zone}/ca.crt"
"#
    )
}

fn prepare_volumes(
    lab_name: &str,
    svc_name: &str,
    volumes: &std::collections::BTreeMap<String, ServiceVolume>,
) -> Result<(Vec<(String, String)>, bool)> {
    let state_dir = service_state_dir(lab_name, svc_name);
    io::fs::create_dir_all(&state_dir)
        .with_context(|| format!("Failed to create state dir: {}", state_dir.display()))?;

    let mut mounts = Vec::new();
    let mut content_changed = false;

    for (container_path, vol) in volumes {
        if let Some(content) = vol.content.as_deref() {
            let filename = container_path.rsplit('/').next().unwrap_or("file");
            let host_path = state_dir.join(filename);

            let existing = io::fs::read_to_string(&host_path).ok();
            if existing.as_deref() != Some(content) {
                content_changed = true;
                io::fs::write(&host_path, content)
                    .with_context(|| format!("Failed to write {}", host_path.display()))?;
            }

            mounts.push((host_path.display().to_string(), container_path.clone()));
        } else if let Some(persist_name) = vol.persist.as_deref() {
            let host_path = state_dir.join(persist_name);
            io::fs::create_dir_all(&host_path)
                .with_context(|| format!("Failed to create persist dir {}", host_path.display()))?;
            #[cfg(unix)]
            {
                let _ = io::fs::set_mode(&host_path, 0o777);
            }
            mounts.push((host_path.display().to_string(), container_path.clone()));
        }
    }

    Ok((mounts, content_changed))
}

pub fn start_service(
    lab_name: &str,
    svc_name: &str,
    svc: &HostService,
    provenance: &crate::domain::provenance::Provenance,
) -> Result<()> {
    let container = svc.container.as_str();
    let image = svc.image.as_str();
    let description = svc.description.as_str();

    if container.is_empty() || image.is_empty() {
        println!(
            "{} Skipping service '{}' (missing container name or image)",
            style(">>>").yellow(),
            svc_name
        );
        return Ok(());
    }

    let (mut volume_mounts, content_changed) = prepare_volumes(lab_name, svc_name, &svc.volumes)?;

    if io::docker::container_running(container) {
        let actual_image = io::docker::container_image(container);
        let actual_ports = io::docker::container_ports(container);
        let labelled_lab = io::docker::container_label(container, crate::domain::provenance::LAB);
        let mut drift = service_drift(
            image,
            actual_image.as_deref(),
            &svc.ports,
            actual_ports.as_deref(),
            labelled_lab.as_deref(),
        );
        if content_changed {
            drift.push("config file contents changed".to_string());
        }

        // A container docker is restarting is not serving anything, whatever
        // its configuration says. Recreating it is what picks up a repair made
        // outside it -- a certificate this run just made readable is mounted
        // into the old container, not the process that failed to open it --
        // and if the cause is still there the fresh start's own check says so.
        if io::docker::container_restarting(container) {
            drift.push("docker is restarting it".to_string());
        }

        if drift.is_empty() {
            println!("{} {} already running", style(">>>").green(), description);
            return Ok(());
        }

        println!(
            "{} {} no longer matches the lab, recreating:",
            style(">>>").yellow(),
            description,
        );
        for line in &drift {
            println!("      - {line}");
        }
        io::docker::stop_container(container)?;
    }

    let ports: Vec<&str> = svc.ports.iter().map(String::as_str).collect();

    add_extra_mounts(lab_name, svc, &mut volume_mounts);

    let mount_refs: Vec<(&str, &str)> = volume_mounts
        .iter()
        .map(|(h, c)| (h.as_str(), c.as_str()))
        .collect();

    let link = svc.link.as_deref();
    let network_mode = svc.network_mode.as_deref();
    let cap_add: Vec<String> = svc.cap_add.clone();
    let networks: Vec<String> = svc.networks.clone();
    let command: Vec<String> = svc.command.clone();
    let network_ips = network_ips(svc);
    let dns_ips = dns_container_ips(svc);

    println!("{} Starting {}...", style(">>>").cyan(), description);

    io::docker::run_container_extended(io::docker::RunContainer {
        name: container,
        image,
        ports: &ports,
        volume_mounts: &mount_refs,
        link,
        networks: &networks.iter().map(String::as_str).collect::<Vec<_>>(),
        dns_ips: &dns_ips,
        command: &command.iter().map(String::as_str).collect::<Vec<_>>(),
        network_mode,
        cap_add: &cap_add.iter().map(String::as_str).collect::<Vec<_>>(),
        network_ips: &network_ips,
        labels: &provenance.labels(svc_name),
    })?;

    wait_for_service_ready(svc, description)?;
    refuse_a_crash_loop(container, description)?;

    println!("{} {} started", style(">>>").green(), description);

    Ok(())
}

/// A container docker has already had to restart did not start.
///
/// `container_running` is true between a crash-looper's attempts, and a
/// service with no `readyProbe` is otherwise never asked anything, so a
/// misconfigured one reads as started and the failure only surfaces much later
/// as every endpoint that routes through it timing out.
fn refuse_a_crash_loop(container: &str, description: &str) -> Result<()> {
    let Some(restarts) = io::docker::container_restart_count(container) else {
        return Ok(());
    };
    if restarts == 0 {
        return Ok(());
    }
    let logs = io::docker::container_logs(container, 20)
        .unwrap_or_else(|| "docker had no output for it".to_string());
    bail!(
        "{description} has restarted {restarts} time(s) since it was started, so it is not running its own configuration:\n\n{logs}"
    );
}

fn add_extra_mounts(lab_name: &str, svc: &HostService, volume_mounts: &mut Vec<(String, String)>) {
    let state_dir = lab_state_dir(lab_name);
    for mount in &svc.extra_mounts {
        let resolved = mount
            .host
            .replace("{{STATE_DIR}}", &state_dir.display().to_string());
        volume_mounts.push((resolved, mount.container.clone()));
    }
}

fn network_ips(svc: &HostService) -> HashMap<String, String> {
    let mut out = HashMap::new();
    if let Some(net_cfg) = svc.network_config.as_object() {
        for (net_name, net_val) in net_cfg {
            if let Some(ip) = net_val["ip"].as_str() {
                out.insert(net_name.clone(), ip.to_string());
            }
        }
    }
    out
}

/// Resolvers a service should use, named by container.
///
/// `first_network_ip`, not `get_container_ip`: the latter reads
/// `.NetworkSettings.IPAddress`, which is only set for the default bridge and
/// is empty for anything on a lab's own network. This path had never been
/// used, so it had never been noticed that it always yielded nothing.
fn dns_container_ips(svc: &HostService) -> Vec<String> {
    svc.dns_containers
        .as_array()
        .map(|arr| {
            arr.iter()
                .filter_map(|v| v.as_str())
                .filter_map(io::docker::first_network_ip)
                .collect()
        })
        .unwrap_or_default()
}

fn parse_probe_timeout(s: &str) -> Duration {
    let secs = match s.split_at(s.len().saturating_sub(1)) {
        (n, "s") => n.parse::<u64>().ok(),
        (n, "m") => n.parse::<u64>().ok().map(|v| v * 60),
        (n, "h") => n.parse::<u64>().ok().map(|v| v * 3600),
        _ => s.parse::<u64>().ok(),
    };
    Duration::from_secs(secs.unwrap_or(60))
}

fn wait_for_service_ready(svc: &HostService, description: &str) -> Result<()> {
    let Some(probe) = svc.ready_probe.as_ref() else {
        return Ok(());
    };
    let kind = probe.kind.as_str();
    let host = probe.host.as_str();
    let port = probe.port;
    let timeout = parse_probe_timeout(probe.timeout.as_deref().unwrap_or("60s"));
    let path = probe.path.as_deref().unwrap_or("/");
    let expected = u64::from(probe.expected_status.unwrap_or(200));

    let addr = format!("{host}:{port}");
    let mut last_err = String::from("never attempted");

    println!(
        "{} Waiting for {description} to serve {kind}://{addr}{}",
        style(">>>").cyan(),
        if kind == "http" { path } else { "" },
    );

    let ready =
        crate::io::poll::poll_while_time_remains(timeout, Duration::from_millis(500), || {
            match probe_once(&addr, kind, host, path, expected) {
                Ok(()) => Some(()),
                Err(e) => {
                    last_err = e.to_string();
                    None
                }
            }
        });
    if ready.is_none() {
        bail!("{description} did not become ready within {timeout:?}: {last_err}");
    }
    Ok(())
}

pub fn probe_once(addr: &str, kind: &str, host: &str, path: &str, expected: u64) -> Result<()> {
    let sock_addr = addr
        .to_socket_addrs()
        .context("resolving readyProbe address")?
        .next()
        .ok_or_else(|| anyhow!("no address resolved for {addr}"))?;
    let mut stream = TcpStream::connect_timeout(&sock_addr, Duration::from_secs(2))?;
    if kind != "http" {
        return Ok(());
    }
    stream.set_read_timeout(Some(Duration::from_secs(5)))?;
    stream.set_write_timeout(Some(Duration::from_secs(5)))?;
    write!(
        stream,
        "GET {path} HTTP/1.1\r\nHost: {host}\r\nConnection: close\r\nUser-Agent: cata-readyprobe\r\n\r\n"
    )?;
    let mut status_line = String::new();
    BufReader::new(&stream).read_line(&mut status_line)?;
    let code: u64 = status_line
        .split_whitespace()
        .nth(1)
        .and_then(|c| c.parse().ok())
        .ok_or_else(|| anyhow!("unparseable status line: {}", status_line.trim()))?;
    if code == expected {
        Ok(())
    } else {
        bail!("got HTTP {code}, want {expected}")
    }
}

#[cfg(test)]
mod tests {
    use std::thread;

    use super::*;
    use std::net::TcpListener;
    use std::sync::mpsc;

    #[test]
    fn parses_wait_nix_durations() {
        assert_eq!(parse_probe_timeout("30s"), Duration::from_secs(30));
        assert_eq!(parse_probe_timeout("2m"), Duration::from_secs(120));
        assert_eq!(parse_probe_timeout("1h"), Duration::from_secs(3600));
        assert_eq!(parse_probe_timeout("garbage"), Duration::from_secs(60));
    }

    struct OneShot {
        port: u16,
        handle: thread::JoinHandle<()>,
    }

    fn one_shot_http(status: u16) -> OneShot {
        let listener = TcpListener::bind("127.0.0.1:0").unwrap();
        let port = listener.local_addr().unwrap().port();
        let (ready, started) = mpsc::channel();
        let handle = thread::spawn(move || {
            ready.send(()).expect("test receiver dropped");
            if let Ok((mut sock, _)) = listener.accept() {
                let _ = sock.set_read_timeout(Some(Duration::from_secs(5)));
                let mut req: Vec<u8> = Vec::new();
                let mut scratch = [0u8; 512];
                loop {
                    match sock.read(&mut scratch) {
                        Ok(0) => break,
                        Ok(n) => {
                            req.extend_from_slice(&scratch[..n]);
                            if req.windows(4).any(|w| w == b"\r\n\r\n") {
                                break;
                            }
                        }
                        Err(_) => break,
                    }
                }
                let _ = write!(sock, "HTTP/1.1 {status} OK\r\nContent-Length: 0\r\n\r\n");
                let _ = sock.flush();
            }
        });
        started
            .recv()
            .expect("one-shot server thread failed to start");
        OneShot { port, handle }
    }

    #[test]
    fn http_probe_accepts_expected_status() {
        let srv = one_shot_http(200);
        let result = probe_once(
            &format!("127.0.0.1:{}", srv.port),
            "http",
            "127.0.0.1",
            "/v2/",
            200,
        );
        srv.handle.join().expect("one-shot server thread panicked");
        assert!(result.is_ok(), "probe failed: {result:?}");
    }

    #[test]
    fn http_probe_rejects_unexpected_status() {
        let srv = one_shot_http(503);
        let err = probe_once(
            &format!("127.0.0.1:{}", srv.port),
            "http",
            "127.0.0.1",
            "/v2/",
            200,
        )
        .unwrap_err()
        .to_string();
        srv.handle.join().expect("one-shot server thread panicked");
        assert!(err.contains("503"), "unexpected error: {err}");
    }

    #[test]
    fn probe_fails_when_nothing_is_listening() {
        assert!(probe_once("127.0.0.1:1", "tcp", "127.0.0.1", "/", 200).is_err());
    }

    #[test]
    fn absent_ready_probe_is_a_no_op() {
        let svc: HostService = serde_json::from_value(serde_json::json!({
            "container": "c",
            "description": "no probe",
            "image": "i",
            "ports": [],
            "volumes": {},
        }))
        .expect("a service without a probe parses");
        assert!(wait_for_service_ready(&svc, "no probe").is_ok());
    }

    #[test]
    fn a_persisted_volume_names_the_docker_volume_rather_than_flagging_one() {
        let svc: HostService = serde_json::from_value(serde_json::json!({
            "container": "registry",
            "description": "registry",
            "image": "zot",
            "ports": ["5050:5000"],
            "volumes": { "/var/lib/zot": { "persist": "data" } },
        }))
        .expect("a service with a persisted volume parses");
        assert_eq!(
            svc.volumes["/var/lib/zot"].persist.as_deref(),
            Some("data"),
            "persist carries the volume name, so a bool would have dropped it"
        );
    }

    #[test]
    fn the_lab_resolver_puts_the_lab_dns_first_and_keeps_public_fallbacks() {
        let conf = lab_resolv_conf("172.19.0.5");
        let nameservers: Vec<&str> = conf
            .lines()
            .filter_map(|l| l.strip_prefix("nameserver "))
            .collect();
        assert_eq!(nameservers, ["172.19.0.5", "1.1.1.1", "8.8.8.8"]);
        assert!(conf.contains("options timeout:1 attempts:1"), "{conf}");
    }
}

/// What no longer matches between a declared service and the container that
/// is running for it.
///
/// A running container used to be compared only against the content of its
/// config files, so bumping the image tag in Nix printed "already running" in
/// green and kept serving the old image. These are recreated rather than
/// refused: they are containers on the operator's workstation, not cluster
/// state, so recreating one is cheap and is already what a config change did.
pub fn service_drift(
    declared_image: &str,
    actual_image: Option<&str>,
    declared_ports: &[String],
    actual_ports: Option<&[String]>,
    labelled_lab: Option<&str>,
) -> Vec<String> {
    let mut drift = Vec::new();

    if labelled_lab.is_none() {
        drift.push(
            "it was created before catallaxy recorded which lab owns a container, \
             so nothing can attribute or clean it up"
                .to_string(),
        );
    }

    match actual_image {
        Some(actual) if actual != declared_image => drift.push(format!(
            "image: declared {declared_image}, running {actual}"
        )),
        _ => {}
    }

    if let Some(actual) = actual_ports {
        let mut declared: Vec<String> = declared_ports
            .iter()
            .map(|p| p.trim_end_matches("/tcp").to_string())
            .collect();
        declared.sort();
        if declared != actual {
            drift.push(format!(
                "ports: declared [{}], publishing [{}]",
                declared.join(", "),
                actual.join(", ")
            ));
        }
    }

    drift
}

#[cfg(test)]
mod drift_tests {

    /// The ingress publishes the same container port twice, on loopback and
    /// on the lab's gateway. Comparing without the address made both sides
    /// read as `80:80`, the declaration never matched, and every `lab up`
    /// rebuilt the container while claiming to be idempotent.
    #[test]
    fn a_port_published_on_two_addresses_is_not_drift() {
        let declared = vec![
            "127.0.0.1:8082:80".to_string(),
            "172.22.0.1:80:80".to_string(),
        ];
        let actual = vec![
            "127.0.0.1:8082:80".to_string(),
            "172.22.0.1:80:80".to_string(),
        ];
        let d = service_drift("img", Some("img"), &declared, Some(&actual), Some("lab"));
        assert!(d.is_empty(), "{d:?}");
    }
    use super::*;

    fn drift(
        image: &str,
        actual: Option<&str>,
        ports: &[String],
        actual_ports: Option<&[String]>,
    ) -> Vec<String> {
        service_drift(image, actual, ports, actual_ports, Some("a-lab"))
    }

    #[test]
    fn a_matching_container_has_no_drift() {
        assert!(
            drift(
                "traefik:v3.3.6",
                Some("traefik:v3.3.6"),
                &["8080:80".to_string()],
                Some(&["8080:80".to_string()])
            )
            .is_empty()
        );
    }

    #[test]
    fn a_container_from_before_labels_is_drift_so_the_next_up_relabels_it() {
        let d = service_drift("img", Some("img"), &[], Some(&[]), None);
        assert_eq!(d.len(), 1);
        assert!(d[0].contains("which lab owns"), "{d:?}");
    }

    // The reported bug: bumping the tag in Nix left the old image serving and
    // printed "already running" in green.
    #[test]
    fn a_bumped_image_tag_is_drift() {
        let drift = drift("traefik:v3.4.0", Some("traefik:v3.3.6"), &[], Some(&[]));
        assert_eq!(drift.len(), 1);
        assert!(drift[0].contains("v3.4.0"), "{drift:?}");
        assert!(drift[0].contains("v3.3.6"), "{drift:?}");
    }

    #[test]
    fn a_changed_port_is_drift() {
        let drift = drift(
            "img",
            Some("img"),
            &["9090:80".to_string()],
            Some(&["8080:80".to_string()]),
        );
        assert_eq!(drift.len(), 1);
        assert!(drift[0].starts_with("ports:"), "{drift:?}");
    }

    #[test]
    fn the_order_docker_lists_ports_in_is_not_a_change() {
        assert!(
            drift(
                "img",
                Some("img"),
                &["9090:90".to_string(), "8080:80".to_string()],
                Some(&["8080:80".to_string(), "9090:90".to_string()])
            )
            .is_empty()
        );
    }

    #[test]
    fn a_tcp_suffix_on_one_side_only_is_not_a_change() {
        assert!(
            drift(
                "img",
                Some("img"),
                &["8080:80/tcp".to_string()],
                Some(&["8080:80".to_string()])
            )
            .is_empty()
        );
    }

    // A container we cannot inspect is not a container that matches.
    #[test]
    fn an_unreadable_container_reports_nothing_rather_than_a_false_match() {
        assert!(drift("img", None, &["8080:80".to_string()], None).is_empty());
    }

    #[test]
    fn several_changes_are_all_reported() {
        let drift = drift(
            "new",
            Some("old"),
            &["9090:80".to_string()],
            Some(&["8080:80".to_string()]),
        );
        assert_eq!(drift.len(), 2);
    }
}
