use std::collections::HashMap;
#[cfg(test)]
use std::io::Read;
use std::io::{BufRead, BufReader, Write};
use std::net::{TcpStream, ToSocketAddrs};
use std::time::Duration;

use anyhow::{Context, Result, anyhow, bail};
use console::style;

use crate::domain::{HostService, ServiceVolume};
use crate::io;

use crate::host::state::{lab_state_dir, service_state_dir};

pub fn k3d_host_endpoint() -> &'static str {
    "host.k3d.internal"
}

pub fn generate_registries_yaml(port: u16, upstreams: &[String]) -> String {
    let host = k3d_host_endpoint();
    let mut body = String::from("mirrors:\n");
    for h in upstreams {
        body.push_str(&format!(
            "  {h}:\n    endpoint: [\"http://{host}:{port}\"]\n"
        ));
    }
    body
}

pub fn lab_resolv_conf(dns_ip: &str) -> String {
    format!(
        "# Auto-generated by catallaxy.\n\
         # Lab DNS (Knot) handles *.<zone>; falls through on REFUSED.\n\
         nameserver {dns_ip}\n\
         nameserver 1.1.1.1\n\
         nameserver 8.8.8.8\n\
         options timeout:1 attempts:1\n"
    )
}

pub fn generate_registry_hosts_toml(zone: &str) -> String {
    format!(
        r#"# Auto-generated by catallaxy. Trusts the lab self-signed CA via
# `ca = ...`, so containerd verifies the Harbor cert against the same
# CA that signed it. DNS is handled by the lab DNS server (the k3d
# node's /etc/resolv.conf points at it), so this hosts.toml's only
# concern is TLS trust — no /etc/hosts hacks, no mirror semantics,
# no `?ns=` query, no `skip_verify`.
server = "https://registry.{zone}"

[host."https://registry.{zone}"]
  capabilities = ["pull", "resolve"]
  ca = "/var/lib/rancher/k3s/agent/etc/containerd/certs.d/registry.{zone}/ca.crt"
"#
    )
}

fn prepare_volumes(
    lab_name: &str,
    svc_name: &str,
    volumes: &std::collections::BTreeMap<String, ServiceVolume>,
) -> Result<(Vec<(String, String)>, bool)> {
    let state_dir = service_state_dir(lab_name, svc_name);
    io::fs::create_dir_all(&state_dir)
        .with_context(|| format!("Failed to create state dir: {}", state_dir.display()))?;

    let mut mounts = Vec::new();
    let mut content_changed = false;

    for (container_path, vol) in volumes {
        if let Some(content) = vol.content.as_deref() {
            let filename = container_path.rsplit('/').next().unwrap_or("file");
            let host_path = state_dir.join(filename);

            let existing = io::fs::read_to_string(&host_path).ok();
            if existing.as_deref() != Some(content) {
                content_changed = true;
                io::fs::write(&host_path, content)
                    .with_context(|| format!("Failed to write {}", host_path.display()))?;
            }

            mounts.push((host_path.display().to_string(), container_path.clone()));
        } else if let Some(persist_name) = vol.persist.as_deref() {
            let host_path = state_dir.join(persist_name);
            io::fs::create_dir_all(&host_path)
                .with_context(|| format!("Failed to create persist dir {}", host_path.display()))?;
            #[cfg(unix)]
            {
                let _ = io::fs::set_mode(&host_path, 0o777);
            }
            mounts.push((host_path.display().to_string(), container_path.clone()));
        }
    }

    Ok((mounts, content_changed))
}

pub fn start_service(lab_name: &str, svc_name: &str, svc: &HostService) -> Result<()> {
    let container = svc.container.as_str();
    let image = svc.image.as_str();
    let description = svc.description.as_str();

    if container.is_empty() || image.is_empty() {
        println!(
            "{} Skipping service '{}' (missing container name or image)",
            style(">>>").yellow(),
            svc_name
        );
        return Ok(());
    }

    let (mut volume_mounts, content_changed) = prepare_volumes(lab_name, svc_name, &svc.volumes)?;

    if io::docker::container_running(container) {
        if content_changed {
            println!(
                "{} {} config changed, recreating...",
                style(">>>").yellow(),
                description,
            );
            io::docker::stop_container(container)?;
        } else {
            println!("{} {} already running", style(">>>").green(), description);
            return Ok(());
        }
    }

    let ports: Vec<&str> = svc.ports.iter().map(String::as_str).collect();

    add_extra_mounts(lab_name, svc, &mut volume_mounts);

    let mount_refs: Vec<(&str, &str)> = volume_mounts
        .iter()
        .map(|(h, c)| (h.as_str(), c.as_str()))
        .collect();

    let link = svc.link.as_deref();
    let network_mode = svc.network_mode.as_deref();
    let cap_add: Vec<String> = svc.cap_add.clone();
    let networks: Vec<String> = svc.networks.clone();
    let command: Vec<String> = svc.command.clone();
    let network_ips = network_ips(svc);
    let dns_ips = dns_container_ips(svc);

    println!("{} Starting {}...", style(">>>").cyan(), description);

    if link.is_some()
        || !networks.is_empty()
        || !dns_ips.is_empty()
        || network_mode.is_some()
        || !cap_add.is_empty()
    {
        io::docker::run_container_extended(io::docker::RunContainer {
            name: container,
            image,
            ports: &ports,
            volume_mounts: &mount_refs,
            link,
            networks: &networks.iter().map(String::as_str).collect::<Vec<_>>(),
            dns_ips: &dns_ips,
            command: &command.iter().map(String::as_str).collect::<Vec<_>>(),
            network_mode,
            cap_add: &cap_add.iter().map(String::as_str).collect::<Vec<_>>(),
            network_ips: &network_ips,
        })?;
    } else {
        io::docker::run_container(
            container,
            image,
            &ports,
            &mount_refs,
            &command.iter().map(String::as_str).collect::<Vec<_>>(),
        )?;
    }

    wait_for_service_ready(svc, description)?;

    println!("{} {} started", style(">>>").green(), description);

    Ok(())
}

fn add_extra_mounts(lab_name: &str, svc: &HostService, volume_mounts: &mut Vec<(String, String)>) {
    let state_dir = lab_state_dir(lab_name);
    for mount in &svc.extra_mounts {
        let resolved = mount
            .host
            .replace("{{STATE_DIR}}", &state_dir.display().to_string());
        volume_mounts.push((resolved, mount.container.clone()));
    }
}

fn network_ips(svc: &HostService) -> HashMap<String, String> {
    let mut out = HashMap::new();
    if let Some(net_cfg) = svc.network_config.as_object() {
        for (net_name, net_val) in net_cfg {
            if let Some(ip) = net_val["ip"].as_str() {
                out.insert(net_name.clone(), ip.to_string());
            }
        }
    }
    out
}

fn dns_container_ips(svc: &HostService) -> Vec<String> {
    svc.dns_containers
        .as_array()
        .map(|arr| {
            arr.iter()
                .filter_map(|v| v.as_str())
                .filter_map(io::docker::get_container_ip)
                .collect()
        })
        .unwrap_or_default()
}

fn parse_probe_timeout(s: &str) -> Duration {
    let secs = match s.split_at(s.len().saturating_sub(1)) {
        (n, "s") => n.parse::<u64>().ok(),
        (n, "m") => n.parse::<u64>().ok().map(|v| v * 60),
        (n, "h") => n.parse::<u64>().ok().map(|v| v * 3600),
        _ => s.parse::<u64>().ok(),
    };
    Duration::from_secs(secs.unwrap_or(60))
}

fn wait_for_service_ready(svc: &HostService, description: &str) -> Result<()> {
    let Some(probe) = svc.ready_probe.as_ref() else {
        return Ok(());
    };
    let kind = probe.kind.as_str();
    let host = probe.host.as_str();
    let port = probe.port;
    let timeout = parse_probe_timeout(probe.timeout.as_deref().unwrap_or("60s"));
    let path = probe.path.as_deref().unwrap_or("/");
    let expected = u64::from(probe.expected_status.unwrap_or(200));

    let addr = format!("{host}:{port}");
    let mut last_err = String::from("never attempted");

    println!(
        "{} Waiting for {description} to serve {kind}://{addr}{}",
        style(">>>").cyan(),
        if kind == "http" { path } else { "" },
    );

    let ready =
        crate::io::poll::poll_while_time_remains(timeout, Duration::from_millis(500), || {
            match probe_once(&addr, kind, host, path, expected) {
                Ok(()) => Some(()),
                Err(e) => {
                    last_err = e.to_string();
                    None
                }
            }
        });
    if ready.is_none() {
        bail!("{description} did not become ready within {timeout:?}: {last_err}");
    }
    Ok(())
}

pub fn probe_once(addr: &str, kind: &str, host: &str, path: &str, expected: u64) -> Result<()> {
    let sock_addr = addr
        .to_socket_addrs()
        .context("resolving readyProbe address")?
        .next()
        .ok_or_else(|| anyhow!("no address resolved for {addr}"))?;
    let mut stream = TcpStream::connect_timeout(&sock_addr, Duration::from_secs(2))?;
    if kind != "http" {
        return Ok(());
    }
    stream.set_read_timeout(Some(Duration::from_secs(5)))?;
    stream.set_write_timeout(Some(Duration::from_secs(5)))?;
    write!(
        stream,
        "GET {path} HTTP/1.1\r\nHost: {host}\r\nConnection: close\r\nUser-Agent: cata-readyprobe\r\n\r\n"
    )?;
    let mut status_line = String::new();
    BufReader::new(&stream).read_line(&mut status_line)?;
    let code: u64 = status_line
        .split_whitespace()
        .nth(1)
        .and_then(|c| c.parse().ok())
        .ok_or_else(|| anyhow!("unparseable status line: {}", status_line.trim()))?;
    if code == expected {
        Ok(())
    } else {
        bail!("got HTTP {code}, want {expected}")
    }
}

#[cfg(test)]
mod tests {
    use std::thread;

    use super::*;
    use std::net::TcpListener;
    use std::sync::mpsc;

    #[test]
    fn parses_wait_nix_durations() {
        assert_eq!(parse_probe_timeout("30s"), Duration::from_secs(30));
        assert_eq!(parse_probe_timeout("2m"), Duration::from_secs(120));
        assert_eq!(parse_probe_timeout("1h"), Duration::from_secs(3600));
        assert_eq!(parse_probe_timeout("garbage"), Duration::from_secs(60));
    }

    struct OneShot {
        port: u16,
        handle: thread::JoinHandle<()>,
    }

    fn one_shot_http(status: u16) -> OneShot {
        let listener = TcpListener::bind("127.0.0.1:0").unwrap();
        let port = listener.local_addr().unwrap().port();
        let (ready, started) = mpsc::channel();
        let handle = thread::spawn(move || {
            ready.send(()).expect("test receiver dropped");
            if let Ok((mut sock, _)) = listener.accept() {
                let _ = sock.set_read_timeout(Some(Duration::from_secs(5)));
                let mut req: Vec<u8> = Vec::new();
                let mut scratch = [0u8; 512];
                loop {
                    match sock.read(&mut scratch) {
                        Ok(0) => break,
                        Ok(n) => {
                            req.extend_from_slice(&scratch[..n]);
                            if req.windows(4).any(|w| w == b"\r\n\r\n") {
                                break;
                            }
                        }
                        Err(_) => break,
                    }
                }
                let _ = write!(sock, "HTTP/1.1 {status} OK\r\nContent-Length: 0\r\n\r\n");
                let _ = sock.flush();
            }
        });
        started
            .recv()
            .expect("one-shot server thread failed to start");
        OneShot { port, handle }
    }

    #[test]
    fn http_probe_accepts_expected_status() {
        let srv = one_shot_http(200);
        let result = probe_once(
            &format!("127.0.0.1:{}", srv.port),
            "http",
            "127.0.0.1",
            "/v2/",
            200,
        );
        srv.handle.join().expect("one-shot server thread panicked");
        assert!(result.is_ok(), "probe failed: {result:?}");
    }

    #[test]
    fn http_probe_rejects_unexpected_status() {
        let srv = one_shot_http(503);
        let err = probe_once(
            &format!("127.0.0.1:{}", srv.port),
            "http",
            "127.0.0.1",
            "/v2/",
            200,
        )
        .unwrap_err()
        .to_string();
        srv.handle.join().expect("one-shot server thread panicked");
        assert!(err.contains("503"), "unexpected error: {err}");
    }

    #[test]
    fn probe_fails_when_nothing_is_listening() {
        assert!(probe_once("127.0.0.1:1", "tcp", "127.0.0.1", "/", 200).is_err());
    }

    #[test]
    fn absent_ready_probe_is_a_no_op() {
        let svc: HostService = serde_json::from_value(serde_json::json!({
            "container": "c",
            "description": "no probe",
            "image": "i",
            "ports": [],
            "volumes": {},
        }))
        .expect("a service without a probe parses");
        assert!(wait_for_service_ready(&svc, "no probe").is_ok());
    }

    #[test]
    fn a_persisted_volume_names_the_docker_volume_rather_than_flagging_one() {
        let svc: HostService = serde_json::from_value(serde_json::json!({
            "container": "registry",
            "description": "registry",
            "image": "zot",
            "ports": ["5050:5000"],
            "volumes": { "/var/lib/zot": { "persist": "data" } },
        }))
        .expect("a service with a persisted volume parses");
        assert_eq!(
            svc.volumes["/var/lib/zot"].persist.as_deref(),
            Some("data"),
            "persist carries the volume name, so a bool would have dropped it"
        );
    }

    #[test]
    fn the_lab_resolver_puts_the_lab_dns_first_and_keeps_public_fallbacks() {
        let conf = lab_resolv_conf("172.19.0.5");
        let nameservers: Vec<&str> = conf
            .lines()
            .filter_map(|l| l.strip_prefix("nameserver "))
            .collect();
        assert_eq!(nameservers, ["172.19.0.5", "1.1.1.1", "8.8.8.8"]);
        assert!(conf.contains("options timeout:1 attempts:1"), "{conf}");
    }
}
