use std::collections::HashMap;
use std::fs;
#[cfg(test)]
use std::io::Read;
use std::io::{BufRead, BufReader, Write};
use std::net::{TcpStream, ToSocketAddrs};
use std::thread;
use std::time::{Duration, Instant};

use anyhow::{Context, Result, anyhow, bail};
use console::style;

use crate::config::Context as CataContext;
use crate::io;

use crate::host::state::{lab_state_dir, service_state_dir};

pub fn k3d_host_endpoint() -> &'static str {
    "host.k3d.internal"
}

pub fn generate_registries_yaml(port: u16, upstreams: &[String]) -> String {
    let host = k3d_host_endpoint();
    let mut body = String::from("mirrors:\n");
    for h in upstreams {
        body.push_str(&format!(
            "  {h}:\n    endpoint: [\"http://{host}:{port}\"]\n"
        ));
    }
    body
}

pub fn generate_registry_hosts_toml(zone: &str) -> String {
    format!(
        r#"# Auto-generated by catallaxy. Trusts the lab self-signed CA via
# `ca = ...`, so containerd verifies the Harbor cert against the same
# CA that signed it. DNS is handled by the lab DNS server (the k3d
# node's /etc/resolv.conf points at it), so this hosts.toml's only
# concern is TLS trust — no /etc/hosts hacks, no mirror semantics,
# no `?ns=` query, no `skip_verify`.
server = "https://registry.{zone}"

[host."https://registry.{zone}"]
  capabilities = ["pull", "resolve"]
  ca = "/var/lib/rancher/k3s/agent/etc/containerd/certs.d/registry.{zone}/ca.crt"
"#
    )
}

fn prepare_volumes(
    lab_name: &str,
    svc_name: &str,
    volumes: &serde_json::Map<String, serde_json::Value>,
) -> Result<(Vec<(String, String)>, bool)> {
    let state_dir = service_state_dir(lab_name, svc_name);
    fs::create_dir_all(&state_dir)
        .with_context(|| format!("Failed to create state dir: {}", state_dir.display()))?;

    let mut mounts = Vec::new();
    let mut content_changed = false;

    for (container_path, vol) in volumes {
        if let Some(content) = vol["content"].as_str() {
            let filename = container_path.rsplit('/').next().unwrap_or("file");
            let host_path = state_dir.join(filename);

            let existing = fs::read_to_string(&host_path).ok();
            if existing.as_deref() != Some(content) {
                content_changed = true;
                fs::write(&host_path, content)
                    .with_context(|| format!("Failed to write {}", host_path.display()))?;
            }

            mounts.push((host_path.display().to_string(), container_path.clone()));
        } else if let Some(persist_name) = vol["persist"].as_str() {
            let host_path = state_dir.join(persist_name);
            fs::create_dir_all(&host_path)
                .with_context(|| format!("Failed to create persist dir {}", host_path.display()))?;
            #[cfg(unix)]
            {
                use std::os::unix::fs::PermissionsExt;
                let _ = fs::set_permissions(&host_path, fs::Permissions::from_mode(0o777));
            }
            mounts.push((host_path.display().to_string(), container_path.clone()));
        }
    }

    Ok((mounts, content_changed))
}

pub fn start_service(
    _ctx: &CataContext,
    lab_name: &str,
    svc_name: &str,
    svc: &serde_json::Value,
) -> Result<()> {
    let container = svc["container"].as_str().unwrap_or("");
    let image = svc["image"].as_str().unwrap_or("");
    let description = svc["description"].as_str().unwrap_or(svc_name);

    if container.is_empty() || image.is_empty() {
        println!(
            "{} Skipping service '{}' (missing container name or image)",
            style(">>>").yellow(),
            svc_name
        );
        return Ok(());
    }

    let (mut volume_mounts, content_changed) = if let Some(volumes) = svc["volumes"].as_object() {
        prepare_volumes(lab_name, svc_name, volumes)?
    } else {
        (Vec::new(), false)
    };

    if io::docker::container_running(container) {
        if content_changed {
            println!(
                "{} {} config changed, recreating...",
                style(">>>").yellow(),
                description,
            );
            io::docker::stop_container(container)?;
        } else {
            println!("{} {} already running", style(">>>").green(), description);
            return Ok(());
        }
    }

    let ports: Vec<&str> = svc["ports"]
        .as_array()
        .map(|arr| arr.iter().filter_map(|v| v.as_str()).collect())
        .unwrap_or_default();

    add_extra_mounts(lab_name, svc, &mut volume_mounts);

    let mount_refs: Vec<(&str, &str)> = volume_mounts
        .iter()
        .map(|(h, c)| (h.as_str(), c.as_str()))
        .collect();

    let link = svc["link"].as_str();
    let network_mode = svc["networkMode"].as_str();
    let cap_add = string_list(svc, "capAdd");
    let networks = string_list(svc, "networks");
    let command = string_list(svc, "command");
    let network_ips = network_ips(svc);
    let dns_ips = dns_container_ips(svc);

    println!("{} Starting {}...", style(">>>").cyan(), description);

    if link.is_some()
        || !networks.is_empty()
        || !dns_ips.is_empty()
        || network_mode.is_some()
        || !cap_add.is_empty()
    {
        io::docker::run_container_extended(io::docker::RunContainer {
            name: container,
            image,
            ports: &ports,
            volume_mounts: &mount_refs,
            link,
            networks: &networks,
            dns_ips: &dns_ips,
            command: &command,
            network_mode,
            cap_add: &cap_add,
            network_ips: &network_ips,
        })?;
    } else {
        io::docker::run_container(container, image, &ports, &mount_refs, &command)?;
    }

    wait_for_service_ready(svc, description)?;

    println!("{} {} started", style(">>>").green(), description);

    Ok(())
}

fn add_extra_mounts(
    lab_name: &str,
    svc: &serde_json::Value,
    volume_mounts: &mut Vec<(String, String)>,
) {
    let Some(extra_mounts) = svc["extraMounts"].as_array() else {
        return;
    };
    let state_dir = lab_state_dir(lab_name);
    for mount in extra_mounts {
        if let (Some(host), Some(container)) = (mount["host"].as_str(), mount["container"].as_str())
        {
            let resolved = host.replace("{{STATE_DIR}}", &state_dir.display().to_string());
            volume_mounts.push((resolved, container.to_string()));
        }
    }
}

fn string_list<'a>(svc: &'a serde_json::Value, key: &str) -> Vec<&'a str> {
    svc[key]
        .as_array()
        .map(|arr| arr.iter().filter_map(|v| v.as_str()).collect())
        .unwrap_or_default()
}

fn network_ips(svc: &serde_json::Value) -> HashMap<String, String> {
    let mut out = HashMap::new();
    if let Some(net_cfg) = svc["networkConfig"].as_object() {
        for (net_name, net_val) in net_cfg {
            if let Some(ip) = net_val["ip"].as_str() {
                out.insert(net_name.clone(), ip.to_string());
            }
        }
    }
    out
}

fn dns_container_ips(svc: &serde_json::Value) -> Vec<String> {
    svc["dnsContainers"]
        .as_array()
        .map(|arr| {
            arr.iter()
                .filter_map(|v| v.as_str())
                .filter_map(io::docker::get_container_ip)
                .collect()
        })
        .unwrap_or_default()
}

fn parse_probe_timeout(s: &str) -> Duration {
    let secs = match s.split_at(s.len().saturating_sub(1)) {
        (n, "s") => n.parse::<u64>().ok(),
        (n, "m") => n.parse::<u64>().ok().map(|v| v * 60),
        (n, "h") => n.parse::<u64>().ok().map(|v| v * 3600),
        _ => s.parse::<u64>().ok(),
    };
    Duration::from_secs(secs.unwrap_or(60))
}

fn wait_for_service_ready(svc: &serde_json::Value, description: &str) -> Result<()> {
    let Some(probe) = svc.get("readyProbe").filter(|p| !p.is_null()) else {
        return Ok(());
    };
    let kind = probe["kind"].as_str().unwrap_or("tcp");
    let host = probe["host"].as_str().unwrap_or("127.0.0.1");
    let Some(port) = probe["port"].as_u64() else {
        bail!("readyProbe for service '{description}' is missing 'port'");
    };
    let timeout = parse_probe_timeout(probe["timeout"].as_str().unwrap_or("60s"));
    let path = probe["path"].as_str().unwrap_or("/");
    let expected = probe["expectedStatus"].as_u64().unwrap_or(200);

    let addr = format!("{host}:{port}");
    let deadline = Instant::now() + timeout;
    let mut last_err = String::from("never attempted");

    println!(
        "{} Waiting for {description} to serve {kind}://{addr}{}",
        style(">>>").cyan(),
        if kind == "http" { path } else { "" },
    );

    while Instant::now() < deadline {
        match probe_once(&addr, kind, host, path, expected) {
            Ok(()) => return Ok(()),
            Err(e) => last_err = e.to_string(),
        }
        thread::sleep(Duration::from_millis(500));
    }
    bail!("{description} did not become ready within {timeout:?}: {last_err}");
}

pub fn probe_once(addr: &str, kind: &str, host: &str, path: &str, expected: u64) -> Result<()> {
    let sock_addr = addr
        .to_socket_addrs()
        .context("resolving readyProbe address")?
        .next()
        .ok_or_else(|| anyhow!("no address resolved for {addr}"))?;
    let mut stream = TcpStream::connect_timeout(&sock_addr, Duration::from_secs(2))?;
    if kind != "http" {
        return Ok(());
    }
    stream.set_read_timeout(Some(Duration::from_secs(5)))?;
    stream.set_write_timeout(Some(Duration::from_secs(5)))?;
    write!(
        stream,
        "GET {path} HTTP/1.1\r\nHost: {host}\r\nConnection: close\r\nUser-Agent: cata-readyprobe\r\n\r\n"
    )?;
    let mut status_line = String::new();
    BufReader::new(&stream).read_line(&mut status_line)?;
    let code: u64 = status_line
        .split_whitespace()
        .nth(1)
        .and_then(|c| c.parse().ok())
        .ok_or_else(|| anyhow!("unparseable status line: {}", status_line.trim()))?;
    if code == expected {
        Ok(())
    } else {
        bail!("got HTTP {code}, want {expected}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::net::TcpListener;
    use std::sync::mpsc;

    #[test]
    fn parses_wait_nix_durations() {
        assert_eq!(parse_probe_timeout("30s"), Duration::from_secs(30));
        assert_eq!(parse_probe_timeout("2m"), Duration::from_secs(120));
        assert_eq!(parse_probe_timeout("1h"), Duration::from_secs(3600));
        assert_eq!(parse_probe_timeout("garbage"), Duration::from_secs(60));
    }

    struct OneShot {
        port: u16,
        handle: thread::JoinHandle<()>,
    }

    fn one_shot_http(status: u16) -> OneShot {
        let listener = TcpListener::bind("127.0.0.1:0").unwrap();
        let port = listener.local_addr().unwrap().port();
        let (ready, started) = mpsc::channel();
        let handle = thread::spawn(move || {
            ready.send(()).expect("test receiver dropped");
            if let Ok((mut sock, _)) = listener.accept() {
                let _ = sock.set_read_timeout(Some(Duration::from_secs(5)));
                let mut req: Vec<u8> = Vec::new();
                let mut scratch = [0u8; 512];
                loop {
                    match sock.read(&mut scratch) {
                        Ok(0) => break,
                        Ok(n) => {
                            req.extend_from_slice(&scratch[..n]);
                            if req.windows(4).any(|w| w == b"\r\n\r\n") {
                                break;
                            }
                        }
                        Err(_) => break,
                    }
                }
                let _ = write!(sock, "HTTP/1.1 {status} OK\r\nContent-Length: 0\r\n\r\n");
                let _ = sock.flush();
            }
        });
        started
            .recv()
            .expect("one-shot server thread failed to start");
        OneShot { port, handle }
    }

    #[test]
    fn http_probe_accepts_expected_status() {
        let srv = one_shot_http(200);
        let result = probe_once(
            &format!("127.0.0.1:{}", srv.port),
            "http",
            "127.0.0.1",
            "/v2/",
            200,
        );
        srv.handle.join().expect("one-shot server thread panicked");
        assert!(result.is_ok(), "probe failed: {result:?}");
    }

    #[test]
    fn http_probe_rejects_unexpected_status() {
        let srv = one_shot_http(503);
        let err = probe_once(
            &format!("127.0.0.1:{}", srv.port),
            "http",
            "127.0.0.1",
            "/v2/",
            200,
        )
        .unwrap_err()
        .to_string();
        srv.handle.join().expect("one-shot server thread panicked");
        assert!(err.contains("503"), "unexpected error: {err}");
    }

    #[test]
    fn probe_fails_when_nothing_is_listening() {
        assert!(probe_once("127.0.0.1:1", "tcp", "127.0.0.1", "/", 200).is_err());
    }

    #[test]
    fn absent_ready_probe_is_a_no_op() {
        let svc = serde_json::json!({ "description": "no probe" });
        assert!(wait_for_service_ready(&svc, "no probe").is_ok());
    }
}
